version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Bratislava
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    rebase-strategy: auto
    commit-message:
      prefix: "chore(deps)"
    groups:
      npm-production-minor-patch:
        dependency-type: production
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      npm-development-minor-patch:
        dependency-type: development
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Bratislava
    open-pull-requests-limit: 3
    rebase-strategy: auto
    commit-message:
      prefix: "chore(actions)"
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
