import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import { installAuthSession } from './uiAuthSession.mjs';

const baseUrl = process.env.KITCHEN_UI_BASE_URL;
if (!baseUrl || !['localhost', '127.0.0.1'].includes(new URL(baseUrl).hostname)) throw new Error('Requires an isolated localhost runtime.');
const ready = await fetch(new URL('/ready', baseUrl));
if (!ready.ok || (await ready.json()).storage !== 'file') throw new Error('Requires disposable file storage.');
const out = '.tmp-doors-ui';
await mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
const errors = [], checks = [];
page.on('pageerror', error => errors.push(String(error)));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
const assert = (ok, message) => { if (!ok) throw new Error(message); checks.push(message); };
const project = point => page.evaluate(p => window.__kitchenDebug.projectPlanPoint(p), point);
let group, id;
const snapshot = () => page.evaluate(g => window.__kitchenDebug.snapshot(g), group);
const module = async () => (await snapshot()).instances.find(item => item.id === id);
const select = () => page.evaluate(id => window.__kitchenDebug.selectModule(id), id);
const samePose = (a, b) => JSON.stringify([a.positionM, a.rotationYRad, a.kitchenPlacement]) === JSON.stringify([b.positionM, b.rotationYRad, b.kitchenPlacement]);
try {
  await installAuthSession(page, { autoStartWorkspace: false });
  await page.goto(baseUrl, { waitUntil: 'domcontentloaded' });
  await page.waitForSelector('[data-project-manager-form]', { state: 'attached' });
  if (!(await page.locator('[data-project-manager-form]').isVisible())) await page.locator('[data-project-manager-new]').click();
  await page.locator("input[name='name']").fill(`QA Doors ${Date.now()}`);
  await page.locator("input[name='address']").fill('QA');
  await page.locator("input[name='contactName']").fill('QA');
  await page.locator('[data-project-manager-form] button[type="submit"]').click();
  await page.waitForFunction(() => !!window.__kitchenDebug);
  const fixture = await page.evaluate(() => window.__kitchenDebug.createKitchenScenario({ path: [{ x: 0, z: 0 }, { x: 4000, z: 0 }], addModule: false }));
  group = fixture.group.id;
  await page.getByRole('button', { name: /^(Upraviť kuchyňu|Edit kitchen)$/ }).click();
  await page.getByRole('button', { name: /^(Pôdorys|Floorplan)$/ }).click();
  await page.getByRole('button', { name: /^(Prispôsobiť pohľad|Fit view)$/ }).click();
  await page.waitForTimeout(800);
  await page.evaluate(() => window.__kitchenDebug.startModulePlacement('fwm_catalog_base_doors'));
  const insert = await project({ x: 1000, z: 300 });
  await page.mouse.move(insert.x, insert.y); await page.waitForTimeout(200);
  assert(await page.evaluate(() => window.__kitchenDebug.placementState().valid), 'Base insertion preview is valid');
  await page.mouse.click(insert.x, insert.y); await page.keyboard.press('Escape');
  id = (await snapshot()).instances[0]?.id;
  assert(!!id, 'Base module inserted through the normal placement owner');

  await page.evaluate(id => window.__kitchenDebug.selectModule(id), id);
  const doorToggle = () => page.getByRole('checkbox', { name: 'Dvierka', exact: true });
  await doorToggle().waitFor();
  assert(await doorToggle().isChecked(), 'Old/default cabinet keeps its doors');
  const before = await module();
  assert(before.parts.some(part => /^door_/.test(part.name)), 'Cabinet initially has actual door parts');
  await doorToggle().uncheck();
  const without = await module();
  assert(without.params.hasDoors === false, 'Checkbox stores explicit false');
  assert(!without.parts.some(part => /^door_/.test(part.name)), 'Checkbox removes actual door geometry');
  assert(without.params.doorCount === before.params.doorCount, 'Door leaf count stays stored');
  assert(without.params.width === before.params.width && without.params.height === before.params.height && without.params.depth === before.params.depth, 'Door removal retains cabinet dimensions');
  await page.keyboard.press('Control+z');
  assert((await module()).parts.some(part => /^door_/.test(part.name)), 'Undo restores door parts');
  await page.keyboard.press('Control+y');
  assert((await module()).params.hasDoors === false, 'Redo restores door removal');
  await page.screenshot({ path: `${out}/without-doors.png` });
  const saveResponse = page.waitForResponse(response => response.url().endsWith('/save') && response.request().method() === 'POST');
  await page.locator("button[data-quick-action='save']").click();
  const response = await saveResponse;
  assert(response.ok(), 'Kitchen without doors saves successfully');
  const saved = (await response.json()).save;
  const download = await page.context().request.get(new URL(`/api/projects/${saved.projectId}/download`, baseUrl).toString());
  assert(download.ok(), 'Kitchen FQP download succeeds');
  const importedResponse = await page.context().request.post(new URL('/api/projects/import', baseUrl).toString(), { data: { envelope: await download.text() } });
  assert(importedResponse.ok(), 'Kitchen FQP import succeeds');
  const imported = (await importedResponse.json()).save;
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.waitForFunction(() => !!window.__kitchenDebug);
  assert((await module()).params.hasDoors === false, 'Reload preserves explicit false');
  assert(!(await module()).parts.some(part => /^door_/.test(part.name)), 'Reload reconstructs geometry without doors');
  await page.locator("button[data-quick-action='open']").click();
  const saveExit = page.locator("[data-project-exit='save']");
  if (await saveExit.isVisible()) await saveExit.click();
  await page.waitForSelector('[data-project-manager-list]');
  await page.getByRole('button', { name: new RegExp(imported.project.name) }).click();
  await page.waitForFunction(() => !!window.__kitchenDebug);
  assert((await module()).params.hasDoors === false, 'Imported kitchen preserves explicit false');
  const reopened = await module();
  assert(reopened.params.width === before.params.width && reopened.params.height === before.params.height && reopened.params.depth === before.params.depth, 'FQP retains free dimensions');
  assert(reopened.params.frontMaterialId === before.params.frontMaterialId && reopened.params.bodyMaterialId === before.params.bodyMaterialId, 'FQP retains materials');
  assert(JSON.stringify(reopened.parts) === JSON.stringify(without.parts), 'FQP reconstructs the same retained parts');
  await select();
  await doorToggle().check();
  assert(JSON.stringify((await module()).parts) === JSON.stringify(before.parts), 'Enabling doors after FQP restores the original parts');
  assert(errors.length === 0, 'Browser console and page errors are zero');
  await writeFile(`${out}/result.json`, JSON.stringify({ checks, errors }, null, 2));
  console.log(`Module doors UI: ${checks.length} checks passed.`);
} catch (error) {
  await page.screenshot({ path: `${out}/failure.png` });
  await writeFile(`${out}/failure.json`, JSON.stringify({ error: String(error), checks, errors, body: await page.locator('body').innerText() }, null, 2));
  throw error;
} finally { await browser.close(); }
