import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import { installAuthSession } from './uiAuthSession.mjs';

const baseUrl = process.env.KITCHEN_UI_BASE_URL;
if (!baseUrl || !['localhost', '127.0.0.1'].includes(new URL(baseUrl).hostname)) throw new Error('Requires an isolated localhost runtime.');
const ready = await fetch(new URL('/ready', baseUrl));
if (!ready.ok || (await ready.json()).storage !== 'file') throw new Error('Requires disposable file storage.');
const out = '.tmp-preset-ui';
await mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
const errors = [], checks = [];
page.on('pageerror', error => errors.push(String(error)));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
const assert = (ok, message) => { if (!ok) throw new Error(message); checks.push(message); };
const project = point => page.evaluate(p => window.__kitchenDebug.projectPlanPoint(p), point);
let group, id;
const snapshot = () => page.evaluate(g => window.__kitchenDebug.snapshot(g), group);
const module = async () => (await snapshot()).instances.find(item => item.id === id);
const select = () => page.evaluate(id => window.__kitchenDebug.selectModule(id), id);
const samePose = (a, b) => JSON.stringify([a.positionM, a.rotationYRad, a.kitchenPlacement]) === JSON.stringify([b.positionM, b.rotationYRad, b.kitchenPlacement]);
try {
  await installAuthSession(page, { autoStartWorkspace: false });
  await page.goto(baseUrl, { waitUntil: 'domcontentloaded' });
  // Persist the fixture through the tenant import API; debug placement alone uses an in-memory package.
  const imported = await page.evaluate(async () => {
    const { extendedFurnitureModulePackages } = await import('/src/system/module-packages/extendedFurniture.ts');
    const modulePackage = extendedFurnitureModulePackages.find(p => p.module.moduleType === 'fwm_catalog_base_drawers');
    const response = await fetch('/api/modules/import', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ package: modulePackage }) });
    return response.ok;
  });
  assert(imported, 'Real cabinet package is assigned to the isolated test tenant');
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.waitForSelector('[data-project-manager-form]', { state: 'attached' });
  if (!(await page.locator('[data-project-manager-form]').isVisible())) await page.locator('[data-project-manager-new]').click();
  await page.locator("input[name='name']").fill(`QA Presets ${Date.now()}`);
  await page.locator("input[name='address']").fill('QA');
  await page.locator("input[name='contactName']").fill('QA');
  await page.locator('[data-project-manager-form] button[type="submit"]').click();
  await page.waitForFunction(() => !!window.__kitchenDebug);
  const fixture = await page.evaluate(() => window.__kitchenDebug.createKitchenScenario({ path: [{ x: 0, z: 0 }, { x: 4000, z: 0 }], addModule: false }));
  group = fixture.group.id;
  await page.getByRole('button', { name: /^(Upraviť kuchyňu|Edit kitchen)$/ }).click();
  await page.getByRole('button', { name: /^(Pôdorys|Floorplan)$/ }).click();
  await page.getByRole('button', { name: /^(Prispôsobiť pohľad|Fit view)$/ }).click();
  await page.waitForTimeout(800);
  await page.evaluate(() => window.__kitchenDebug.startModulePlacement('fwm_catalog_base_drawers'));
  const insert = await project({ x: 1000, z: 300 });
  await page.mouse.move(insert.x, insert.y); await page.waitForTimeout(200);
  assert(await page.evaluate(() => window.__kitchenDebug.placementState().valid), 'Base insertion preview is valid');
  await page.mouse.click(insert.x, insert.y); await page.keyboard.press('Escape');
  id = (await snapshot()).instances[0]?.id;
  assert(!!id, 'Base module inserted through the normal placement owner');

  await select();
  const trigger = () => page.locator('[data-module-parameter-preset-trigger]');
  await trigger().scrollIntoViewIfNeeded();
  await page.waitForSelector('[data-module-parameter-preset-trigger] [data-preview-state="ready"]', { timeout: 30000 });
  await trigger().click();
  const card = () => page.locator('[data-parameter-preset-id="drawers_2_top_shallow"]');
  await card().scrollIntoViewIfNeeded();
  await card().locator('[data-preview-state="ready"]').waitFor({ timeout: 30000 });
  const initial = await card().locator('img').getAttribute('src');
  assert(initial.startsWith('data:image/png'), 'Preset uses a rendered geometry image');
  await page.screenshot({ path: `${out}/options-before.png` });
  await card().click();
  assert((await module()).params.drawerCount === 2, 'Selecting a preset applies its configuration');
  await trigger().scrollIntoViewIfNeeded();
  await trigger().locator('[data-preview-state="ready"]').waitFor({ timeout: 30000 });
  const appliedImage = await trigger().locator('img').getAttribute('src');
  assert(initial === appliedImage, 'Preset preview matches the applied geometry');
  await page.evaluate(id => window.__kitchenDebug.patchModuleParams(id, { width: 1100 }, { sourceKey: 'width' }), id);
  await select();
  await trigger().scrollIntoViewIfNeeded();
  await trigger().locator('[data-preview-state="ready"]').waitFor({ timeout: 30000 });
  const resizedImage = await trigger().locator('img').getAttribute('src');
  assert(resizedImage !== appliedImage, 'Resizing regenerates the actual preview');
  await trigger().click();
  await card().scrollIntoViewIfNeeded();
  await card().locator('[data-preview-state="ready"]').waitFor({ timeout: 30000 });
  assert(await card().locator('img').getAttribute('src') === resizedImage, 'Options and current configuration use the same resized geometry');
  await page.screenshot({ path: `${out}/options-resized.png` });
  await trigger().click();
  const source = await module();
  await page.evaluate(id => window.__kitchenDebug.patchModuleParams(id, { hasDoors: false }), id);
  await select();
  const presetName = `QA custom ${Date.now()}`;
  await page.locator('.module-parameter-preset-create').click();
  const dialog = () => page.locator('form').filter({ has: page.locator('textarea[placeholder="Note"]') });
  await dialog().locator('input[placeholder="Name"]').fill(presetName);
  await dialog().locator('textarea').fill('Saved configuration regression');
  const [createdResponse] = await Promise.all([
    page.waitForResponse(response => response.url().endsWith('/parameter-presets') && response.request().method() === 'POST'),
    dialog().locator('button[type="submit"]').click(),
  ]);
  assert(createdResponse.ok(), 'Create preset endpoint succeeds');
  const created = await createdResponse.json();
  const presetId = created.preset.presetId;
  const savedPreset = created.modulePackage.parameterPresets.presets.find(preset => preset.presetId === presetId);
  assert(savedPreset.parameterValues.drawerCount === 2, 'Created preset stores configuration');
  assert(savedPreset.parameterValues.hasDoors === false, 'Created preset stores disabled doors as false');
  assert(!Object.hasOwn(savedPreset.parameterValues, 'width'), 'Created preset leaves width free');
  assert(!Object.hasOwn(savedPreset.parameterValues, 'frontMaterialId'), 'Created preset leaves materials free');
  await trigger().scrollIntoViewIfNeeded();
  assert((await trigger().textContent()).includes(presetName), 'Created preset becomes immediately available');
  await page.evaluate(g => window.__kitchenDebug.addKitchenModule(g, { type: 'fwm_catalog_base_drawers', offsetAlongMm: 2500 }), group);
  id = (await snapshot()).instances.find(item => item.id !== source.id).id;
  await page.evaluate(id => window.__kitchenDebug.patchModuleParams(id, { width: 750 }, { sourceKey: 'width' }), id);
  await select();
  const targetBefore = await module();
  await trigger().scrollIntoViewIfNeeded(); await trigger().click();
  const customCard = () => page.locator(`[data-parameter-preset-id="${presetId}"]`);
  await customCard().scrollIntoViewIfNeeded();
  await customCard().locator('[data-preview-state="ready"]').waitFor({ timeout: 30000 });
  const targetPreview = await customCard().locator('img').getAttribute('src');
  await customCard().click();
  const targetAfter = await module();
  assert(targetAfter.params.drawerCount === 2 && targetAfter.params.width === targetBefore.params.width, 'Preset applies to another cabinet while retaining its width');
  assert(targetAfter.params.hasDoors === false, 'Preset applies disabled doors to another cabinet');
  assert(targetAfter.params.frontMaterialId === targetBefore.params.frontMaterialId && targetAfter.params.bodyMaterialId === targetBefore.params.bodyMaterialId, 'Preset retains target materials');
  await trigger().scrollIntoViewIfNeeded();
  await trigger().locator('[data-preview-state="ready"]').waitFor({ timeout: 30000 });
  assert(await trigger().locator('img').getAttribute('src') === targetPreview, 'Saved preset preview equals its applied result on the other cabinet');
  const [savedResponse] = await Promise.all([
    page.waitForResponse(response => response.url().endsWith('/save') && response.request().method() === 'POST'),
    page.locator("button[data-quick-action='save']").click(),
  ]);
  assert(savedResponse.ok(), 'Project with applied preset saves');
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.waitForFunction(() => !!window.__kitchenDebug);
  await select();
  await trigger().scrollIntoViewIfNeeded(); await trigger().click();
  assert(await customCard().count() === 1, 'Saved preset survives page reload');
  assert((await module()).params.hasDoors === false, 'Applied door configuration survives project reload');
  await trigger().click();
  await page.route('**/parameter-presets', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ ok: false, error: 'QA saving unavailable' }) }));
  await page.locator('.module-parameter-preset-create').click();
  await dialog().locator('input[placeholder="Name"]').fill('QA rejected preset');
  await dialog().locator('textarea').fill('Controlled save failure');
  await dialog().locator('button[type="submit"]').click();
  await dialog().getByText('QA saving unavailable', { exact: true }).waitFor();
  assert(await dialog().locator('button[type="submit"]').isEnabled(), 'Failed save remains visible and retryable');
  assert((await module()).params.hasDoors === false, 'Failed preset save leaves the cabinet unchanged');
  await dialog().getByRole('button', { name: /^(Zrušiť|Cancel)$/ }).click();
  await page.unroute('**/parameter-presets');
  const exportedIcon = await page.evaluate(async () => {
    const { resolveArcigyModuleIconTargets } = await import('/src/modules/fwmFurniture/moduleIconRenderContract.ts');
    await import('/scripts/arcigyModuleIconRenderer.ts');
    return (await window.renderArcigyModuleIcons([resolveArcigyModuleIconTargets([])[0].id]))[0];
  });
  assert(exportedIcon.dataUrl.startsWith('data:image/png'), 'Catalog export uses the shared renderer successfully');
  assert(exportedIcon.hasTransparentBackground, 'Shared renderer preserves the standard transparent catalog background');
  await writeFile(`${out}/canonical-export.png`, Buffer.from(exportedIcon.dataUrl.split(',')[1], 'base64'));
  assert(errors.length === 0, 'Browser console and page errors are zero');
  await writeFile(`${out}/result.json`, JSON.stringify({ checks, errors }, null, 2));
  console.log(`Module presets UI: ${checks.length} checks passed.`);
} catch (error) {
  await page.screenshot({ path: `${out}/failure.png` });
  await writeFile(`${out}/failure.json`, JSON.stringify({ error: String(error), checks, errors, body: await page.locator('body').innerText() }, null, 2));
  throw error;
} finally { await browser.close(); }
