import { describe,it,expect } from "vitest";
import { Mesh, MeshBasicMaterial, DoubleSide, Raycaster, Vector3 } from "three";
import { generateBacksplash,synchronizeBacksplash,resetBacksplashBoard,type BacksplashInput } from "./generator";
import type { BacksplashGroupSource,CustomFurnitureParams } from "../customFurnitureTypes";
import { customBoardNetAreaMm2 } from "../customBoardProfile";
import { makeCustomFurnitureBoardGeometry,polygonBoundsMm } from "../customFurnitureGeometry";
import { customBoardEdges } from "../customFurnitureEdges";
export const rectangle=(x:number,z:number,w:number,d:number)=>[{x,z},{x:x+w,z},{x:x+w,z:z+d},{x,z:z+d}];
export function inputFixture():BacksplashInput{return{kitchenId:"k",fallbackTopMm:1500,walls:[{id:"wall",params:{aMm:{x:0,z:0},bMm:{x:3600,z:0},thicknessMm:200,heightMm:2600,materialId:"wall",justification:"interior",exteriorSign:-1}}],worktops:[{id:"wt",surfaceMm:900,polygons:[rectangle(0,0,2400,600)]}],cabinets:[{id:"a",role:"base",footprint:rectangle(0,0,600,600),bottomMm:0,wallIds:["wall"]},{id:"b",role:"base",footprint:rectangle(1200,0,1200,600),bottomMm:0,wallIds:["wall"]}],openings:[]};}
export function sourceFixture():BacksplashGroupSource{return{kitchenId:"k",wallIds:["wall"],materialId:"board",thicknessMm:18,offsetMm:0,kerfMm:3,allowHalf:true,grain:"length",maxLengthMm:2800,joints:{},suppressedKeys:[],orphanedWallIds:[]};}
export function paramsFixture():CustomFurnitureParams{return{name:"Zástena",groupKind:"backsplash",backsplash:sourceFixture(),boards:[],boundary:rectangle(0,0,2400,100),baseConstraint:"absolute",baseOffsetMm:0,topConstraint:"absolute",topOffsetMm:1500};}
describe("automatic backsplash geometry and lifecycle",()=>{
 it("does not continue into unsupported worktop coverage beyond a tall cabinet",()=>{
   const input=inputFixture();input.worktops[0]!.polygons=[rectangle(0,0,3600,600)];input.cabinets=[input.cabinets[0]!,{id:"tall",role:"tall",footprint:rectangle(1200,0,600,600),bottomMm:0,wallIds:["wall"]}];
   const boards=generateBacksplash(input,sourceFixture());expect(boards).toHaveLength(1);expect(polygonBoundsMm(boards[0]!.profile).maxX).toBe(1200);
 });
 it("recalculates the butt joint against an individually changed thickness and its reset",()=>{
   const input=inputFixture(),params=paramsFixture();input.walls[0]!.params.bMm.x=2400;
   input.walls.push({id:"wall2",params:{...input.walls[0]!.params,aMm:{x:2400,z:0},bMm:{x:2400,z:2400}}});
   input.worktops[0]!.polygons.push(rectangle(1800,0,600,2400));input.cabinets.push({id:"side",role:"base",footprint:rectangle(1800,600,600,1200),bottomMm:0,wallIds:["wall2"]});params.backsplash!.wallIds.push("wall2");
   synchronizeBacksplash(params,input);const first=params.boards.find(b=>b.backsplashSource!.wallId==="wall")!;
   const second=()=>params.boards.find(b=>b.backsplashSource!.wallId==="wall2")!;
   expect(polygonBoundsMm(second().profile).minX).toBe(18);first.thicknessMm=30;synchronizeBacksplash(params,input);
   expect(polygonBoundsMm(second().profile).minX).toBe(30);resetBacksplashBoard(first,"thicknessMm");synchronizeBacksplash(params,input);
   expect(polygonBoundsMm(second().profile).minX).toBe(18);
 });
 it("bridges the appliance gap under one worktop and stops at worktop coverage",()=>{const boards=generateBacksplash(inputFixture(),sourceFixture());expect(boards).toHaveLength(1);expect(polygonBoundsMm(boards[0]!.profile)).toMatchObject({widthMm:2400,heightMm:600,minY:900});});
 it("ignores an island, unrelated wall and a worktop without base cabinets",()=>{const input=inputFixture();input.worktops.push({id:"island",surfaceMm:900,polygons:[rectangle(0,1800,1800,800)]});input.walls.push({id:"unrelated",params:{...input.walls[0]!.params,aMm:{x:0,z:5000},bMm:{x:3000,z:5000}}});const source=sourceFixture();source.wallIds.push("unrelated");expect(generateBacksplash(input,source)).toHaveLength(1);input.cabinets=[];expect(generateBacksplash(input,source)).toHaveLength(0);});
 it("cuts out tall cabinets and follows actual upper bottoms and worktop height",()=>{const input=inputFixture();input.worktops[0]!.surfaceMm=940;input.cabinets.push({id:"tall",role:"tall",footprint:rectangle(1800,0,600,600),bottomMm:0,wallIds:["wall"]},{id:"up",role:"upper",footprint:rectangle(0,0,600,350),bottomMm:1450,wallIds:["wall"]},{id:"up2",role:"upper",footprint:rectangle(600,0,600,350),bottomMm:1600,wallIds:["wall"]});const board=generateBacksplash(input,sourceFixture())[0]!;expect(polygonBoundsMm(board.profile).maxX).toBe(1800);expect(customBoardNetAreaMm2(board)).toBe(600*(510+660+560));});
 it("subtracts windows and doors from the mesh as well as area, retaining the manufacturing blank",()=>{const input=inputFixture();input.openings=[{id:"win",wallId:"wall",centerMm:700,widthMm:400,bottomMm:1100,heightMm:300},{id:"door",wallId:"wall",centerMm:1800,widthMm:600,bottomMm:0,heightMm:2200}];const board=generateBacksplash(input,sourceFixture())[0]!;expect(customBoardNetAreaMm2(board)).toBe(2400*600-400*300-600*600);expect(polygonBoundsMm(board.profile).widthMm).toBe(2400);
   const geometry=makeCustomFurnitureBoardGeometry(board),material=new MeshBasicMaterial({side:DoubleSide}),mesh=new Mesh(geometry,material);mesh.updateMatrixWorld(true);
   const hit=(x:number,y:number)=>new Raycaster(new Vector3(x/1000,y/1000,1),new Vector3(0,0,-1)).intersectObject(mesh).length;
   expect(hit(700,1200)).toBe(0);expect(hit(1800,1200)).toBe(0);expect(hit(100,1200)).toBeGreaterThan(0);expect(customBoardEdges(board).length).toBeGreaterThan(4);geometry.dispose();material.dispose();
 });
 it("places the same profile on an angled wall",()=>{const input=inputFixture(),angle=Math.PI/4,rotate=(p:{x:number;z:number})=>({x:p.x*Math.cos(angle)-p.z*Math.sin(angle),z:p.x*Math.sin(angle)+p.z*Math.cos(angle)});input.walls[0]!.params.bMm=rotate(input.walls[0]!.params.bMm);input.worktops[0]!.polygons=input.worktops[0]!.polygons.map(r=>r.map(rotate));input.cabinets.forEach(c=>c.footprint=c.footprint.map(rotate));const board=generateBacksplash(input,sourceFixture())[0]!;expect(polygonBoundsMm(board.profile).widthMm).toBe(2400);expect(customBoardNetAreaMm2(board)).toBe(1440000);});
 it.each([2,3])("generates %i connected walls with butt corners and no overlapping corner volume",count=>{const input=inputFixture();input.walls[0]!.params.bMm.x=2400;input.walls.push({id:"wall2",params:{...input.walls[0]!.params,aMm:{x:2400,z:0},bMm:{x:2400,z:2400}}});input.worktops[0]!.polygons.push(rectangle(1800,0,600,2400));input.cabinets.push({id:"side",role:"base",footprint:rectangle(1800,600,600,1200),bottomMm:0,wallIds:["wall2"]});if(count===3){input.walls.push({id:"wall3",params:{...input.walls[0]!.params,aMm:{x:2400,z:2400},bMm:{x:0,z:2400}}});input.worktops[0]!.polygons.push(rectangle(0,1800,2400,600));input.cabinets.push({id:"last",role:"base",footprint:rectangle(600,1800,1200,600),bottomMm:0,wallIds:["wall3"]});}const source=sourceFixture();source.wallIds=input.walls.map(w=>w.id);const boards=generateBacksplash(input,source);expect(boards).toHaveLength(count);expect(boards.filter(b=>polygonBoundsMm(b.profile).widthMm<2400)).toHaveLength(count-1);});
 it("proposes joints at cabinet boundaries and accepts explicit wall-local joints",()=>{const input=inputFixture();input.worktops[0]!.polygons=[rectangle(0,0,3600,600)];const source=sourceFixture();source.maxLengthMm=2000;let boards=generateBacksplash(input,source);expect(polygonBoundsMm(boards[0]!.profile).maxX).toBe(1200);source.joints["wall:1"]=[1500];boards=generateBacksplash(input,source);expect(polygonBoundsMm(boards[0]!.profile).maxX).toBe(1500);});
 it("updates existing identities, preserves manual parameters, resets, suppresses deletions and freezes missing sources",()=>{const input=inputFixture(),params=paramsFixture();synchronizeBacksplash(params,input);const id=params.boards[0]!.id;params.boards[0]!.thicknessMm=25;input.worktops[0]!.surfaceMm=920;synchronizeBacksplash(params,input);expect(params.boards[0]!.id).toBe(id);expect(params.boards[0]!.thicknessMm).toBe(25);expect(params.boards[0]!.baseOffsetMm).toBe(920);resetBacksplashBoard(params.boards[0]!,"thicknessMm");expect(params.boards[0]!.thicknessMm).toBe(18);const saved=JSON.parse(JSON.stringify(params));expect(synchronizeBacksplash(saved,input)).toBe(false);const before=JSON.stringify(saved.boards);synchronizeBacksplash(saved,null);expect(JSON.stringify(saved.boards)).toBe(before);expect(saved.backsplash.detached).toBe(true);input.walls=[];synchronizeBacksplash(params,input);expect(params.boards).toHaveLength(1);expect(params.backsplash!.orphanedWallIds).toEqual(["wall"]);params.backsplash!.suppressedKeys.push(params.boards[0]!.backsplashSource!.key);params.boards=[];synchronizeBacksplash(params,inputFixture());expect(params.boards).toHaveLength(0);});
 it("updates automatic openings alongside a custom cutout and retains a removed automatic cutout",()=>{const input=inputFixture(),params=paramsFixture();input.openings=[{id:"w",wallId:"wall",centerMm:700,widthMm:400,bottomMm:1100,heightMm:300}];synchronizeBacksplash(params,input);const board=params.boards[0]!;board.cutouts!.push({id:"own",profile:[{x:10,y:1000},{x:30,y:1000},{x:30,y:1020},{x:10,y:1020}]});input.openings[0]!.centerMm=800;synchronizeBacksplash(params,input);expect(board.cutouts![0]!.profile[0]!.x).toBe(600);expect(board.cutouts).toHaveLength(2);board.cutouts=board.cutouts!.filter(c=>!c.sourceOpeningId);synchronizeBacksplash(params,input);expect(board.cutouts).toHaveLength(1);input.openings[0]!.centerMm=900;synchronizeBacksplash(params,input);expect(board.cutouts).toHaveLength(1);resetBacksplashBoard(board,"cutouts");expect(board.cutouts).toHaveLength(1);expect(board.cutouts![0]!.sourceOpeningId).toBe("w");});
});
